ASTRA_DB_API_ENDPOINT = "YOUR_ASTRA_DB_API_ENDPOINT"
ASTRA_DB_APPLICATION_TOKEN = "YOUR_ASTRA_DB_APPLICATION_TOKEN"
ASTRA_DB_COLLECTION_NAME = "YOUR_ASTRA_DB_COLLECTION_NAME"
ASTRA_DB_PID_COLLECTION_NAME = "YOUR_ASTRA_DB_PID_COLLECTION_NAME"

SPOTIFY_CLIENT_ID = "YOUR_SPOTIFY_CLIENT_ID"
SPOTIFY_CLIENT_SECRET = "YOUR_SPOTIFY_CLIENT_SECRET"

OPENAI_API_KEY = "YOUR_OPENAI_API_KEY"